version: '3'
services:
    server:
        container_name: "${APP_SLUG}-server"
        image: ghcr.io/andreazorzi/PicoLink:latest
        restart: unless-stopped
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
        build:
            context: ./
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
          APP_ENV: 'production'
          APP_DEBUG: 'false'
        env_file:
            - stack.env
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        container_name: "${APP_SLUG}-db"
        image: 'mysql/mysql-server:8.0'
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        env_file:
            - stack.env
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
